fix: Count all MNs when calculating voting threshold
darkcoin/darkcoin pull request #5584
Opened 2023-09-26 17:01 UTC by UdjinM6

## Issue being fixed or feature implemented
This is an alternative to https://github.com/dashpay/dash/pull/5583

## What was done?
Adjust threshold calculations (instead of ignoring votes form invalid MNs)

## How Has This Been Tested?

## Breaking Changes
Proposals will need 441 absolute YES votes (vs 374 now). A couple of currently passing proposals won't pass in this version (unless they get more YES votes).

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-09-26 17:25 UTC, knst commented on src/qt/governancelist.cpp
>          // count total valid (ENABLED) masternodes to determine passing threshold.
```suggestion
        // count total registered masternodes to determine passing threshold.
```

2023-09-27 07:54 UTC, ogabrielides reviewed
ACK. This solution seems more straightforward.
Minor suggestion

2023-09-27 07:54 UTC, ogabrielides commented on src/governance/governance.cpp
>      // count total valid (ENABLED) masternodes to determine passing threshold.
```suggestion
    // count total registered masternodes to determine passing threshold.
```

2023-09-27 08:38 UTC, ogabrielides approved these changes
LGTM

2023-09-28 13:07 UTC, PastaPastaPasta requested changes
NACK we should not be changing the threshold in such a way that requires 40+ more votes for stuff to pass.

2025-07-28 17:07 UTC, DashCoreAutoGuix commented
## ℹ️ Not a Bitcoin Backport

This PR implements a **Dash-specific governance fix** and is not a Bitcoin backport, therefore it does not require backport verification.

**Changes Summary:**
- Modified voting threshold calculation to count all registered masternodes instead of only valid/enabled ones
- Added new `GetWeightedMNsCount()` method to count all masternodes
- Updated governance logic in `governance.cpp`, `governancelist.cpp`, and `governance.cpp` RPC

**Reviewed commit hash:** `32485da735-verify-1753722470`

This PR should be reviewed using standard Dash development practices rather than Bitcoin backport verification.

2026-08-03 17:15 UTC, closed without merging