backport: bitcoin#19988 - Overhaul transaction request logic
darkcoin/darkcoin pull request #5943
Opened 2024-03-19 17:22 UTC by knst

This replaces the transaction request logic with an encapsulated class that maintains all the state surrounding it. By keeping it stand alone, it can be easily tested (using included unit tests and fuzz tests).

The major changes are:

    Announcements from outbound (and whitelisted) peers are now always preferred over those from inbound peers. This used to be the case for the first request (by delaying the first request from inbound peers), and a bias afters. The 2s delay for requests from inbound peers still exists, but after that, if viable outbound peers remain for any given transaction, they will always be tried first.
    No more hard cap of 100 in flight transactions per peer, as there is less need for it (memory usage is linear in the number of announcements, but independent from the number in flight, and CPU usage isn't affected by it). Furthermore, if only one peer announces a transaction, and it has over 100 in flight already, we still want to request it from them. The cap is replaced with a rule that announcements from such overloaded peers get an additional 2s delay (possibly combined with the existing 2s delays for inbound connections, and for txid peers when wtxid peers are available).
    The limit of 100000 tracked announcements is reduced to 5000; this was excessive. This can be bypassed using the PF_RELAY permission (to accommodate locally dumping a batch of many transactions).

## What was done?
 - backport bitcoin/bitcoin#19988

It is not trivial to backport, not trivial to debug and probably won't be easy for review. Dedicated PR is created for this backport only.

## How Has This Been Tested?
Run unit/functional tests

## Breaking Changes

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone

2025-07-28 17:36 UTC, DashCoreAutoGuix commented
## ❌ Backport Verification - Issues Detected
**Original Bitcoin commit:** `89359089fd` (bitcoin#19988)
**Reviewed commit hash:** `a2459bb672-verify-1753724153`

Issues found:
- **File operation validation failed**: 20 violations including 1 critical missing file (`src/net.cpp`)
- **MCP tool confusion**: Initially identified wrong Bitcoin commit (6bc1eca01b for bitcoin#22144 instead of 89359089fd for bitcoin#19988)
- **Merge conflicts**: GitHub Actions reports conflicts, PR needs rebase
- **No CI status**: No checks reported on the branch
- **Missing Bitcoin changes**: Expected ~2438 additions/232 deletions based on Bitcoin commit, but PR seems to have massive scope expansion

The Bitcoin commit shows a clean 15-file change adding transaction request logic, but this PR has extensive modifications to Dash-specific modules (governance, LLMQ, spork) that weren't part of the original Bitcoin change.

<details>
<summary>❌ File Operation Violations</summary>

Critical missing files:
- `src/net.cpp` (Bitcoin modified, Dash PR missing)

Extra Dash-specific files not in Bitcoin:
- Multiple LLMQ files (governance.cpp, chainlocks.cpp, etc.)
- Spork system modifications
- Extensive Makefile changes

</details>

Please address these issues:
1. Rebase the PR to resolve conflicts
2. Review the Bitcoin commit scope vs current PR scope
3. Ensure all Bitcoin changes are included (especially `src/net.cpp`)
4. Consider if Dash-specific adaptations are necessary or scope creep

Re-run verification after addressing these issues.
EOF < /dev/null

2026-07-17 18:48 UTC, thepastaclaw commented
<!-- thepastaclaw-gate v1 -->
⛔ Blockers found — Sonnet deferred (commit 1aed44a4)
_Canonical validated blockers: 1_

2026-07-18 01:51 UTC, thepastaclaw requested changes
<!-- thepastaclaw-review v1 -->
<!-- thepastaclaw-review-phase v1 phase=final sha=256fde99c9424d40fc9729de5bd0e6fc51287dba -->
## Final validation — Codex + Sonnet

This is a backport of bitcoin#19988 (TxRequestTracker overhaul) generalized to Dash's full CInv-based object types. Both Codex and Sonnet specialists independently verified the functional Dash adaptations (delay policy, per-type expiry, consume-once ReceivedResponse wiring, retained MAX_PEER_OBJECT_ANNOUNCEMENTS cap, retained limitedmap for ChainLocks) are correct and no upstream backport prerequisites are missing. Independent git forensics confirm a real, verifiable commit-hygiene defect: the sole commit in this range is a single-parent commit dressed up as a genuine GitHub merge commit, squashing 9 upstream Pieter Wuille commits into one commit attributed solely to the backporter, which is anomalous compared to every other 'Merge #NNNN' commit sampled in this repository's history (all of which are real 2-parent merges).

### Review provenance
- Codex reviewers: `gpt-5.6-sol` — general (failed), `gpt-5.6-sol` — general (failed), `gpt-5.6-sol` — general (failed), `gpt-5.6-sol` — dash-core-commit-history (failed), `gpt-5.6-sol` — dash-core-commit-history (failed), `gpt-5.6-sol` — dash-core-commit-history (failed), `gpt-5.6-sol` — backport-reviewer (failed), `gpt-5.6-sol` — backport-reviewer (failed), `gpt-5.6-sol` — backport-reviewer (failed), `gpt-5.6-sol` — general (completed), `gpt-5.6-sol` — dash-core-commit-history (completed), `gpt-5.6-sol` — backport-reviewer (completed)
- Verifier: `claude-sonnet-5` — verifier
- Sonnet reviewers: `claude-sonnet-5` — general (failed), `claude-sonnet-5` — general (failed), `claude-sonnet-5` — general (completed), `claude-sonnet-5` — dash-core-commit-history (failed), `claude-sonnet-5` — dash-core-commit-history (failed), `claude-sonnet-5` — dash-core-commit-history (completed), `claude-sonnet-5` — backport-reviewer (failed), `claude-sonnet-5` — backport-reviewer (failed), `claude-sonnet-5` — backport-reviewer (completed)

🔴 1 blocking

_1 additional finding(s) omitted (not in diff)._

<details>
<summary>🤖 Prompt for all review comments with AI agents</summary>

```
These findings are from an automated code review. Verify each finding against the current code and only fix it if needed.

In `<commit:256fde99c94>`:
- [BLOCKING] <commit:256fde99c94>:1: Single squashed commit masquerades as a genuine 9-commit merge, losing upstream authorship, bisectability, and message accuracy
  Commit 256fde99c9424d40fc9729de5bd0e6fc51287dba is titled 'Merge #19988: Overhaul transaction request logic' and its body lists 9 upstream Bitcoin Core commits by SHA/author (all Pieter Wuille), formatted exactly like a genuine GitHub merge commit. But `git cat-file -p 256fde99c94` shows only one `parent` line (ca2912d9024836e825cdd3e8cc4db83926c3790f) — this is not an actual merge, and `git rev-list --count ca2912d..256fde9` confirms exactly 1 commit in the range. Sampling ~30 other 'Merge #NNNN' commits in this repository's history (ca2912d9024, 58cc1771eed, f2b15fbfe84, 912e64e8b8f, 94d00f70f65, etc.) shows every single one is a real 2-parent merge; this commit is the sole anomaly. The result: all 9 upstream commits plus the Dash-specific CInv-generalization adaptations (governance/InstantSend/ChainLock/spork/CoinJoin object-type support, ReceivedResponse consume-once semantics, MAX_PEER_OBJECT_ANNOUNCEMENTS retention, limitedmap retention, p2p_tx_download.py mocktime port) are bundled into one indivisible ~2367-line commit authored/committed entirely by the backporter, with `git blame` now attributing Pieter Wuille's networking-behavior rewrite to someone else and `git bisect` unable to isolate which of the 9 logical upstream steps or which Dash adaptation introduced a regression in a codepath Dash also uses for InstantSend locks, ChainLocks, governance votes, and quorum messages. This also explains why the copied upstream message is materially misleading on its own terms: it claims the announcement limit is reduced to 5000 and that 86f50ed10f66 deletes limitedmap, while the actual Dash diff retains the larger MAX_PEER_OBJECT_ANNOUNCEMENTS cap and keeps limitedmap for the ChainLock handler, with no adaptations section explaining either divergence or the CInv generalization. This directly contradicts this project's stated convention to keep backport commits close to 1:1 and preserve original Bitcoin Core authorship/messages per commit. Recommend re-splitting into the individual upstream commits (each with `cherry picked from commit <sha>` trailers and original Pieter Wuille authorship preserved) followed by a separate, clearly-labeled Dash-adaptation commit that documents the retained cap, retained limitedmap, and CInv generalization — consistent with how other backports in this repository are structured.
```
</details>

2026-07-21 08:54 UTC, knst commented on src/net_processing.cpp
> +    const bool overloaded = m_object_request.CountInFlight(node.GetId()) >= MAX_PEER_OBJECT_REQUEST_IN_FLIGHT;
This matches Bitcoin Core #19988 as merged — the overload delay keys on CountInFlight (REQUESTED only) by design; the order-dependence was raised and deliberately accepted upstream (the "overloaded"-counting-candidates experiment was reverted before merge). The fan-out is still bounded: a single peer can only be sent what it announced, chunked by MAX_GETDATA_SZ per SendMessages pass, and each hash is requested from one peer at a time. Dash keeps the higher MAX_PEER_OBJECT_ANNOUNCEMENTS (2×MAX_INV_SZ) because governance vote sync legitimately queues that many — documented as an intentional divergence.

2026-07-21 08:59 UTC, knst commented on src/net_processing.cpp
> +            m_object_request.ReceivedInv(peer->m_id, CInv(MSG_TX, txid), /*preferred=*/true, current_time);
Fixed by checking for nullptr

2026-07-21 09:00 UTC, knst commented on src/net_processing.cpp
> +    m_object_request.ReceivedInv(node.GetId(), inv, preferred, current_time + delay);
fixed

2026-07-21 09:00 UTC, knst commented on test/functional/p2p_tx_download.py
> +        self.wait_until(tx_in_node1_mempool)
fixed

2026-07-21 09:00 UTC, knst commented on test/functional/p2p_tx_download.py
> +        peer.send_message(msg_notfound(vec=[CInv(MSG_TX, 1)]))
fixed

2026-07-23 21:44 UTC, thepastaclaw requested changes
<!-- thepastaclaw-review v1 -->
<!-- thepastaclaw-review-phase v1 phase=preliminary sha=36c2887f7cd715ae4bfacf7721abdbc54d8f709d -->
## Preliminary review — Codex only

The backport remains blocked by the previously reported history-fidelity issue and by an InstantSend retry regression that discards live fallback announcements outside the four peers re-registered for retry. The current head also broadens the non-preferred transaction delay to MSG_DSTX despite the PR's documented Dash adaptation policy, so that behavior should either be restored or explicitly justified and tested.

Validated blockers were found in the Codex precheck. Sonnet is deferred until a fresh Codex revalidation clears the blocker gate.

### Review provenance
- Codex reviewers: `gpt-5.6-sol` — general (completed), `gpt-5.6-sol` — dash-core-commit-history (completed), `gpt-5.6-sol` — backport-reviewer (completed)
- Verifier: `gpt-5.6-sol` — verifier
- Sonnet: **not run (deferred by blocker gate)**

🔴 2 blocking | 🟡 1 suggestion(s)

_1 additional finding(s) omitted (not in diff)._

<details>
<summary>🤖 Prompt for all review comments with AI agents</summary>

```
These findings are from an automated code review. Verify each finding against the current code and only fix it if needed.

In `<commit:8fb303d2f75>`:
- [BLOCKING] <commit:8fb303d2f75>:1: Single squashed commit masquerades as a genuine 9-commit merge, losing upstream authorship, bisectability, and message accuracy
  Commit 8fb303d2f7520c978353a542bd615f693cd97406 still has only one parent and is the sole commit over ba143fe163a7dd37cd8222cb1fb61f12ac7f4410, but its `Merge #19988` message enumerates nine separate upstream commits authored by Pieter Wuille. The combined 16-file backport is authored by Konstantin Akimov, so the upstream authorship and logical boundaries needed for blame and bisect are not preserved. The copied message is also inaccurate for this tree: it says the announcement limit was reduced to 5000 while the code retains `max(5000, 2 * MAX_INV_SZ)`, which is 100000 here, and it lists deletion of limitedmap even though `src/limitedmap.h` remains in use by the ChainLock handler. Reconstruct the upstream commit series with its original authorship and messages, followed by clearly identified Dash adaptation commits.

In `src/net_processing.cpp`:
- [BLOCKING] src/net_processing.cpp:2342-2355: Preserve fallback announcements when forcing an ISLock transaction retry
  The comment says this clears completed leftovers, but `ForgetTxHash()` erases every candidate, requested, and completed announcement for both transaction inventory identities across all peers. `AskPeersForTransaction()` then re-registers only MSG_TX candidates for at most four peers. Any additional connected peers that had already advertised the transaction are removed from the tracker; if the selected four withhold, fail, or disconnect, no remaining peer can be selected unless it independently reannounces. The pre-backport force path left other peers' queued announcements intact. Add tracker support for resetting the stale state required by this retry while preserving live fallback candidates, or rebuild every preserved announcement before clearing the existing state.
- [SUGGESTION] src/net_processing.cpp:1550-1557: Backport adaptation regression: MSG_DSTX announcements now receive NONPREF_PEER_TX_DELAY
  `CInv::IsGenTxMsg()` matches both MSG_TX and MSG_DSTX, so non-preferred inbound DSTX announcements now receive the two-second delay. The merge-base implementation and the previously reviewed head both used `IsMsgTx()`, and the PR description explicitly documents that only MSG_TX receives this delay to preserve existing Dash behavior. This also delays orphan-parent retrieval, which deliberately uses MSG_DSTX to retain possible CoinJoin metadata. Restore the documented MSG_TX-only condition, or explicitly revise the adaptation policy and add functional coverage for the intended DSTX timing.
```
</details>

2026-07-23 21:44 UTC, thepastaclaw commented on src/net_processing.cpp
> +            m_object_request.ReceivedInv(peer->m_id, CInv(MSG_TX, txid), /*preferred=*/true, current_time);
<!-- thepastaclaw-review v1 finding=93b4452feaa5 dedupe=97b4feec052ec16e -->
**🔴 Blocking: Preserve fallback announcements when forcing an ISLock transaction retry**

The comment says this clears completed leftovers, but `ForgetTxHash()` erases every candidate, requested, and completed announcement for both transaction inventory identities across all peers. `AskPeersForTransaction()` then re-registers only MSG_TX candidates for at most four peers. Any additional connected peers that had already advertised the transaction are removed from the tracker; if the selected four withhold, fail, or disconnect, no remaining peer can be selected unless it independently reannounces. The pre-backport force path left other peers' queued announcements intact. Add tracker support for resetting the stale state required by this retry while preserving live fallback candidates, or rebuild every preserved announcement before clearing the existing state.

<sub>source: ['codex']</sub>

2026-07-23 21:44 UTC, thepastaclaw commented on src/net_processing.cpp
> +    if (inv.IsGenTxMsg() && !preferred && m_nodeman == nullptr) delay += NONPREF_PEER_TX_DELAY;
<!-- thepastaclaw-review v1 finding=d89db86695c7 dedupe=e769e5f270b4d59c -->
**🟡 Suggestion: Backport adaptation regression: MSG_DSTX announcements now receive NONPREF_PEER_TX_DELAY**

`CInv::IsGenTxMsg()` matches both MSG_TX and MSG_DSTX, so non-preferred inbound DSTX announcements now receive the two-second delay. The merge-base implementation and the previously reviewed head both used `IsMsgTx()`, and the PR description explicitly documents that only MSG_TX receives this delay to preserve existing Dash behavior. This also delays orphan-parent retrieval, which deliberately uses MSG_DSTX to retain possible CoinJoin metadata. Restore the documented MSG_TX-only condition, or explicitly revise the adaptation policy and add functional coverage for the intended DSTX timing.

```suggestion
    //   - NONPREF_PEER_TX_DELAY for MSG_TX announcements from non-preferred connections.
    //     Dash-specific object types, including MSG_DSTX, are not delayed, and neither is
    //     anything in masternode mode.
    //   - OVERLOADED_PEER_OBJECT_DELAY for announcements from peers which have at least
    //     MAX_PEER_OBJECT_REQUEST_IN_FLIGHT requests in flight.
    const bool preferred = state->fPreferredDownload;
    auto delay{0us};
    if (inv.IsMsgTx() && !preferred && m_nodeman == nullptr) delay += NONPREF_PEER_TX_DELAY;
```

<sub>source: ['codex']</sub>

2026-07-24 09:59 UTC, knst commented on src/net_processing.cpp
> +    if (inv.IsGenTxMsg() && !preferred && m_nodeman == nullptr) delay += NONPREF_PEER_TX_DELAY;
Good catch, fixed. Reverted IsGenTxMsg() back to IsMsgTx() so only MSG_TX is delayed

2026-07-24 10:00 UTC, knst commented on src/net_processing.cpp
> +            m_object_request.ReceivedInv(peer->m_id, CInv(MSG_TX, txid), /*preferred=*/true, current_time);
fixed by dropping both ForgetTxHash calls rather than scoping them.

2026-07-24 17:14 UTC, thepastaclaw requested changes
<!-- thepastaclaw-review v1 -->
<!-- thepastaclaw-review-phase v1 phase=preliminary sha=1aed44a45c28ed37cb0ab10fe048dfd2de253794 -->
## Preliminary review — Codex only

The latest head fixes both previously reported runtime adaptation issues: InstantSend retries preserve fallback announcements, and the non-preferred delay is again restricted to MSG_TX. The #19988 backport remains blocked because nine upstream commits are still collapsed into one single-parent, backporter-authored commit with misleading unadapted message content. The latest partial #20171 commit also has a subject that claims a test addition although its patch only removes redundant locking.

Validated blockers were found in the Codex precheck. Sonnet is deferred until a fresh Codex revalidation clears the blocker gate.

### Review provenance
- Codex reviewers: `gpt-5.6-sol` — general (completed), `gpt-5.6-sol` — specialist (completed), `gpt-5.6-sol` — specialist (completed)
- Verifier: `claude-sonnet-5` — verifier
- Sonnet: **not run (deferred by blocker gate)**

🔴 1 blocking | 🟡 1 suggestion(s)

_2 additional finding(s) omitted (not in diff)._

<details>
<summary>🤖 Prompt for all review comments with AI agents</summary>

```
These findings are from an automated code review. Verify each finding against the current code and only fix it if needed.

In `<commit:0c5f6b39ab3>`:
- [BLOCKING] <commit:0c5f6b39ab3>:1: Single squashed commit masquerades as a genuine 9-commit merge, losing upstream authorship, bisectability, and message accuracy
  Commit 0c5f6b39ab39e79db86823b998574a90a1f1e8a1 has only parent ba143fe163a7dd37cd8222cb1fb61f12ac7f4410, and `git rev-list --count ba143fe163a..0c5f6b39ab3` returns 1. Its message nevertheless enumerates nine separate upstream commits authored by Pieter Wuille, while the combined 16-file, 2382-insertion/363-deletion change is recorded under Konstantin Akimov without the original authorship or logical commit boundaries. The copied description also does not describe the resulting Dash adaptation accurately: it claims the announcement limit was reduced to 5000, but `MAX_INV_SZ` is 50000 and `MAX_PEER_OBJECT_ANNOUNCEMENTS` is `max(5000, 2 * MAX_INV_SZ)`, yielding 100000; it also lists deletion of limitedmap even though `src/chainlock/handler.h` still uses it. Reconstruct the nine upstream commits with their original authorship, subjects, and provenance, then place the Dash-specific CInv generalization and retained-cap/limitedmap changes in clearly identified adaptation commits.

In `<commit:1aed44a45c2>`:
- [SUGGESTION] <commit:1aed44a45c2>:1: Partial #20171 commit subject claims a test addition but only removes redundant locking
  Commit 1aed44a45c28ed37cb0ab10fe048dfd2de253794 is titled `partial Merge #20171: Add functional test test_txid_inv_delay`, but its complete patch is eight deletions from `test/functional/p2p_tx_download.py`. The body identifies the selected upstream change as `bc4a23008762702ffcd6868bcdb8fe2a732640ba Remove redundant p2p lock tacking for tx download functional tests` and states that #19988 already added the test coverage. Use a subject describing the change actually contained in this partial backport, while retaining the bitcoin#20171 and upstream-SHA provenance in the body.
```
</details>

2026-07-24 23:28 UTC, merged